direction: up

IRC.shape: cloud
IRC.style.multiple: true
Websocket.shape: cloud
Websocket.style.multiple: true
IRCConnection.style.multiple: true
WebsocketConnection.style.multiple: true
Hub.inbox.shape: queue

IRC <> IRCConnection
Websocket <> WebsocketConnection
IRCConnection -> Hub.inbox
Socket -> Hub.inbox
WebsocketConnection -> Hub.inbox
Hub.inbox -> Hub.update
Hub.Model -> Hub.update -> Hub.Model
Hub.update -> Hub.View
Keyboard -> Hub.inbox

Kakoune <> GoldfishCLI <> Socket
