direction: right
wrapper.stdin.shape: text

wrapper.stdin -> goldfish.unix socket

goldfish {
	irc connection.style.multiple: true
	irc room.style.multiple: true

   unix socket -- hub
	irc connection -- hub
   irc connection -- irc room
	hub -- irc room
}
